name: Test

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build
      
  GetChangeDetails:
    needs: build
    runs-on: ubuntu-latest
    name: Servicenow Get Change Details

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Servicenow Get Change Details
        uses: ./ 
        id: get
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          change-details: '{"pipeline_name":"maheshganji/custom-action-get/CustomActionGetWorkflow","stage_name":"ServiceNow Change Approval","build_number":"3732116819/attempts/1"}'
      - name: Output of GetChangeDetails
        run: echo "The Status of Update Change Request Details => ${{ steps.get.outputs.change-request-number }}"
